### ISSUE TITLE
vue调试工具

### ISSUE THREAD

**Issue by isnl** [huiyan-fe/mapV-editor#4]
请问vue调试工具如何开启呢

**Comment by Junior2Ran** [comment]
1. 安装vue调试工具
2. 打开开发者工具-选择vue

**Comment by isnl** [comment]
![image](https://user-images.githubusercontent.com/35526117/59996511-21045d00-968d-11e9-958d-b735a3d6648f.png)
已经安装过了，启动工程后不显示

**Comment by Junior2Ran** [comment]
插件颜色是灰色的，意味着不可用，这应该是插件的问题，具体原因应该跟进插件的开发方
